// import { User, Post } from "./types";

// export const dummyUsers: User[] = [
//   {
//     id: "1",
//     username: "alice123",
//     name: "Alice Smith",
//     image:
//       "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=334&q=80",
//     bio: "Frontend developer & cat lover.",
//   },
//   {
//     id: "2",
//     username: "bob_dev",
//     name: "Bob Johnson",
//     image:
//       "https://images.unsplash.com/photo-1536164261511-3a17e671d380?auto=format&fit=crop&w=330&q=80",
//     bio: "Full-stack developer, JS enthusiast.",
//   },
//   {
//     id: "3",
//     username: "charlie.tech",
//     name: "Charlie Davis",
//     image:
//       "https://images.unsplash.com/photo-1554780336-390462301acf?auto=format&fit=crop&w=334&q=80",
//     bio: "Tech writer and blogger.",
//   },
//   {
//     id: "4",
//     username: "dana.designs",
//     name: "Dana Lee",
//     image:
//       "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=334&q=80",
//     bio: "UX/UI designer at a startup.",
//   },
//   {
//     id: "5",
//     username: "evan_codes",
//     name: "Evan Martinez",
//     image:
//       "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=334&q=80",
//     bio: "Backend engineer, coffee nerd.",
//   },
// ];

// export const dummyPosts: Post[] = [
//   {
//     id: "1",
//     createdAt: "2025-05-13T10:00:00Z",
//     content: "Just launched my new portfolio site!",
//     user_id: "1",
//     user: dummyUsers[0],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "2",
//     createdAt: "2025-05-14T10:10:00Z",
//     content: "Congrats! Looks awesome.",
//     user_id: "2",
//     user: dummyUsers[1],
//     parent_id: "1",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "3",
//     createdAt: "2025-05-14T10:15:00Z",
//     content: "Thanks! Took a while but worth it.",
//     user_id: "1",
//     user: dummyUsers[0],
//     parent_id: "2",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "4",
//     createdAt: "2025-05-15T09:00:00Z",
//     content: "Why do people still use jQuery?",
//     user_id: "3",
//     user: dummyUsers[2],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "5",
//     createdAt: "2025-05-15T10:00:00Z",
//     content: "Legacy projects, mostly.",
//     user_id: "5",
//     user: dummyUsers[4],
//     parent_id: "4",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "6",
//     createdAt: "2025-05-03T11:00:00Z",
//     content: "I still use jQuery for quick prototypes!",
//     user_id: "2",
//     user: dummyUsers[1],
//     parent_id: "4",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "7",
//     createdAt: "2025-05-04T13:00:00Z",
//     content: "CSS Grid or Flexbox? Go!",
//     user_id: "4",
//     user: dummyUsers[3],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "8",
//     createdAt: "2025-05-04T13:10:00Z",
//     content: "Grid for layout, Flexbox for components!",
//     user_id: "1",
//     user: dummyUsers[0],
//     parent_id: "7",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "9",
//     createdAt: "2025-05-10T08:45:00Z",
//     content: "Who else is hyped for React 19?",
//     user_id: "5",
//     user: dummyUsers[4],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "10",
//     createdAt: "2025-05-10T09:00:00Z",
//     content: "Absolutely! So many cool features.",
//     user_id: "3",
//     user: dummyUsers[2],
//     parent_id: "9",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "11",
//     createdAt: "2025-05-06T14:00:00Z",
//     content: "Anyone using Astro in production?",
//     user_id: "2",
//     user: dummyUsers[1],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "12",
//     createdAt: "2025-05-06T14:05:00Z",
//     content: "Yes! Super fast and developer-friendly.",
//     user_id: "4",
//     user: dummyUsers[3],
//     parent_id: "11",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "13",
//     createdAt: "2025-05-07T10:00:00Z",
//     content: "Learning Rust. Wish me luck!",
//     user_id: "3",
//     user: dummyUsers[2],
//     parent_id: null,
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "14",
//     createdAt: "2025-05-07T10:10:00Z",
//     content: "You got this 💪",
//     user_id: "1",
//     user: dummyUsers[0],
//     parent_id: "13",
//     parent: null,
//     replies: [],
//   },
//   {
//     id: "15",
//     createdAt: "2025-05-07T10:12:00Z",
//     content: "Rust is amazing for performance. Good luck!",
//     user_id: "5",
//     user: dummyUsers[4],
//     parent_id: "13",
//     parent: null,
//     replies: [],
//   },
// ];
